### ISSUE TITLE
decoder returns error with noise models

### ISSUE THREAD

**Issue by aasfaw** [Phionx/qiskit_surface_codes#7]
This is great work, and I'm testing it for integration with other projects within qiskit. When noise models of significant amplitude are used, for example using the test harness (`3_testing_and_noise_models`), the decoder returns an error. Here is an example:

```
for i in range(10):
    print("====Run", i, "====")
    full_loop(code, decoder1, decoder2, noise_model=get_noise(0.1))
    print("=============", "\n")
```

returns different errors each time it is executed, but they all point to the same point in `fitters.py`:

```
====Run 0 ====
Raw readout: {'111101110 01001011 01010010 01011000': 1}
Parsed X: [(2, 2.5, 1.5)]
Parsed Z: [(0, 0.5, 0.5), (0, 0.5, 2.5), (0, 1.5, -0.5), (1, 1.5, -0.5), (1, 1.5, 1.5), (2, 0.5, 2.5), (2, 1.5, -0.5)]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-10-1dab31d2f569> in <module>
      1 for i in range(10):
      2     print("====Run", i, "====")
----> 3     full_loop(code, decoder1, decoder2, noise_model=get_noise(0.1))
      4     print("=============", "\n")

<ipython-input-5-e58737e1f698> in full_loop(code, decoder1, decoder2, noise_model)
     26             matching_graph = decoder.matching_graph(error_graph,'Z')
     27             matches = decoder.matching(matching_graph,'Z')
---> 28             _, paths = decoder.make_error_graph(X_errors, "Z")
     29             flips_z = decoder.calculate_qubit_flips(matches, paths,'Z')
     30         else:

~/code/qiskit_surface_codes/surface_code/fitters.py in make_error_graph(self, nodes, error_key, err_prob)
    320                 error_graph.add_node(
    321                     node,
--> 322                     virtual=virtual_dict[node],
    323                     pos=(node[2], -node[1]),
    324                     time=time_dict[node],

KeyError: (2, 2.5, 1.5)
```

The code in this instance had `d, T = 3, 3` and that location is valid (it is the bottom-most X-syndrome qubit).

This error doesn't show up when noise models are disabled.

**Comment by aasfaw** [comment]
[tagging @liuhenry @ZhenghaoDing @shraggy]

**Comment by liuhenry** [comment]
Thanks @aasfaw! We'll check this out

**Comment by aasfaw** [comment]
I think I spotted the issue. In the test harness, you have the following lines:

![image](https://user-images.githubusercontent.com/1460033/86543297-473d1980-beeb-11ea-9d81-8b8e64475ece.png)

the fourth line has `X_errors` in the `Z_errors` code block, and I think that's the issue here. Replacing that with `Z_errors` seems to fix it.

**Comment by Phionx** [comment]
@liuhenry  and I fixed this issue. It seemed like it was a small typo. We have also clarified the differences between simulated and analytic decoder error correction with comments in tutorial 3.
